name: pengyou

services:
  webapp:
    container_name: pengyou
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ORIGIN=http://localhost:3000
      - MONGO_URL=mongodb://mongodb:27017/pengyou
    ports:
      - 3000:3000
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongodb/db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/pengyou --quiet
      interval: 10s
      timeout: 10s
      retries: 5
